version: "3.4"

services:
  ecom-api:
    container_name: app
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /node_modules
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
