version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run:
          command: pnpm install
          name: install dependencies
      - run:
          command: pnpm build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
