version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:19.5.0

    environment:
      GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ vars.GOOGLE_CLIENT_SECRET }}
      SESSION_SECRET: ${{ vars.SESSION_SECRET }}
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          command: yarn install
          name: install dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: yarn run test
          name: Test app
      - run:
          command: yarn run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_backend:
    jobs:
      - build_and_test
