version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - run:
          command: npm install
          name: install dependencies
      - run:
          command: npm run build
          name: Build app
      - run:
          command: npm run test
          name: Test app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
