paths:
  # search for a product
  /api/v1/product/search:
    get:
      tags: [Product Routes]
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: The name/title of the product
        - in: query
          name: category
          schema:
            type: string
          description: The items matching a certain category
        - in: query
          name: minPrice
          schema:
            type: string
          description: The minimum price in a range
        - in: query
          name: maxPrice
          schema:
            type: string
          description: The maximum price in a range
      responses:
        200:
          description: A list of search results
  /api/v1/product/delete/{id}:
    delete:
      summary: delete a product
      tags: [Product endpoints]
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        201:
          description: Product deleted
        401:
          description: Unauthorized
        400:
          description: product not availble