name: Code Coverage

on:
  push:
    branches:
      - "develop"
      - "main"
  pull_request:
    branches:
      - "develop"
      - "main"

env:
  GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ vars.GOOGLE_CLIENT_SECRET }}
  TEST_DB_URL: ${{vars.TEST_DB_URL}}
  SECRET_TOKEN: ${{vars.GOOGLE_CLIENT_SECRET}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@master
        with:
          version: 16.x

      - name: npm install.
        run: npm install

      - name: check build.
        run: npm run build

      - name: Coveralls Finished

        run: env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run coverage --if-present
