name: Code Coverage

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

env: 
  GOOGLE_CLIENT_ID: 980095536473-pu54ujvdvvr1h33118fq4jprsio9fipd.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@master
        with:
          version: 18.x

      - name: npm install.
        run: npm install

      - name: check build.
        run: npm run build

      - name: Coveralls Finished

        run: env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run coverage --if-present
