name: Test Coveralls

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 18.x
      uses: actions/setup-node@master
      with:
        version: 18.x
        
    - name: Install pnpm
      run: npm install -g pnpm
      
    - run: pnpm ci
    - run: pnpm run build --if-present
    - run: pnpm test
    - name: Coverage Report
      run: env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} pnpm run coverage --if-present
